const { Resend } = require('resend');
const pdfService = require('./pdfService');
const fmcsaService = require('./fmcsaService');

const RESEND_API_KEY = process.env.RESEND_API_KEY;
const FROM_EMAIL = process.env.RESEND_FROM_EMAIL || 'onboarding@resend.dev';

function isConfigured() {
  return RESEND_API_KEY && RESEND_API_KEY.startsWith('re_') && !RESEND_API_KEY.includes('placeholder');
}

async function sendCarrierReport(email, dotNumber, mcNumber) {
  const carrier = await fmcsaService.searchCarrier({ dotNumber, mcNumber });
  const pdf = await pdfService.generateCarrierReport(carrier);

  if (!isConfigured()) {
    console.log(`[DEV] Would send carrier report email to ${email} for DOT ${carrier.dotNumber} (${pdf.length} bytes PDF)`);
    return { id: 'dev_mock' };
  }

  const resend = new Resend(RESEND_API_KEY);

  const { data, error } = await resend.emails.send({
    from: FROM_EMAIL,
    to: email,
    subject: `CarrierGuard AI Report — ${carrier.legalName} (DOT ${carrier.dotNumber})`,
    text: `Hi,\n\nAttached is the compliance report for ${carrier.legalName} (DOT ${carrier.dotNumber}).\n\nRisk Score: ${carrier.riskScore}/100\nSafety Rating: ${carrier.safetyRating}\n\nGenerated by CarrierGuard AI`,
    attachments: [
      {
        filename: `carrier_report_${carrier.dotNumber}.pdf`,
        content: pdf.toString('base64'),
      },
    ],
  });

  if (error) throw error;
  return data;
}

module.exports = { sendCarrierReport };
