const PDFDocument = require('pdfkit');

function generateCarrierReport(carrier) {
  const doc = new PDFDocument({ margin: 50, size: 'A4' });

  const buffers = [];
  doc.on('data', (chunk) => buffers.push(chunk));

  return new Promise((resolve) => {
    doc.on('end', () => resolve(Buffer.concat(buffers)));

    const primary = '#2563eb';
    const gray = '#6b7280';
    const green = '#16a34a';
    const yellow = '#ca8a04';
    const red = '#dc2626';

    doc.font('Helvetica-Bold').fontSize(22).fillColor(primary).text('CarrierGuard AI', { continued: false });
    doc.fontSize(10).fillColor(gray).text('Carrier Compliance Report', { continued: false });
    doc.text(`  |  ${new Date().toLocaleDateString()}`, { align: 'right' });
    doc.moveDown(0.5);
    doc.moveTo(50, doc.y).lineTo(545, doc.y).strokeColor('#e5e7eb').stroke();
    doc.moveDown(1);

    doc.fontSize(18).fillColor('#111827').text(carrier.legalName);
    doc.fontSize(10).fillColor(gray).text(`DOT: ${carrier.dotNumber}  |  MC: ${carrier.mcNumber}`);
    doc.text(`${carrier.city}, ${carrier.state} ${carrier.zip}`);
    doc.moveDown(1);

    const riskColor = carrier.riskScore >= 70 ? green : carrier.riskScore >= 40 ? yellow : red;
    doc.fontSize(12).fillColor('#111827').text('Risk Score');
    doc.font('Helvetica-Bold').fontSize(28).fillColor(riskColor).text(`${carrier.riskScore}/100`);
    doc.moveDown(1);

    doc.font('Helvetica-Bold').fontSize(14).fillColor('#111827').text('Safety & Compliance');
    doc.moveDown(0.3);
    doc.font('Helvetica').fontSize(10).fillColor('#111827');
    doc.text(`Safety Rating: ${carrier.safetyRating}`);
    doc.text(`Authority Status: ${carrier.authorityStatus}`);
    doc.text(`Out of Service Rate: ${carrier.vehicleOOSRate}`);
    doc.text(`Driver OOS Rate: ${carrier.driverOOSRate}`);
    doc.moveDown(0.5);

    doc.font('Helvetica-Bold').fontSize(14).fillColor('#111827').text('Crash & Inspection History');
    doc.moveDown(0.3);
    doc.font('Helvetica').fontSize(10).fillColor('#111827');
    doc.text(`Total Crashes (24mo): ${carrier.crashTotal} (Fatal: ${carrier.fatalCrashes}, Injury: ${carrier.injuryCrashes})`);
    doc.text(`Inspections: ${carrier.inspections}`);
    doc.text(`Violations: ${carrier.violations}`);
    doc.text(`Fleet: ${carrier.powerUnits} power units, ${carrier.drivers} drivers`);
    doc.moveDown(0.5);

    doc.font('Helvetica-Bold').fontSize(14).fillColor('#111827').text('Insurance');
    doc.moveDown(0.3);
    doc.font('Helvetica').fontSize(10).fillColor('#111827');
    if (carrier.insurance && carrier.insurance.length > 0) {
      carrier.insurance.forEach((p) => {
        doc.text(`${p.policyType}: ${p.limit} (${p.carrier}) - ${p.status}`);
      });
    } else {
      doc.text('No insurance records on file.');
    }
    doc.moveDown(0.5);

    doc.font('Helvetica-Bold').fontSize(14).fillColor('#111827').text('AI Compliance Summary');
    doc.moveDown(0.3);
    doc.font('Helvetica').fontSize(10).fillColor('#111827');
    doc.text(carrier.aiSummary || 'No summary available.', { width: 495 });
    doc.moveDown(1);

    doc.moveTo(50, doc.y).lineTo(545, doc.y).strokeColor('#e5e7eb').stroke();
    doc.moveDown(0.5);
    doc.fontSize(8).fillColor(gray).text('Generated by CarrierGuard AI | This report is an automated assessment and does not constitute legal advice.', { align: 'center' });

    doc.end();
  });
}

module.exports = { generateCarrierReport };
